# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ammaar.git-recall
PackageVersion: 1.6.1
InstallerType: portable
Commands:
- git-recall
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AmmaarBakshi/git-recall/releases/download/v1.6.1/git-recall.exe
  InstallerSha256: 5AB94ABCFCD101B2FE0BF2D290A77A54E388D270A1C00FAF0591792B0BAD9832
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-28
